### ISSUE TITLE
Changing the optimizer fails

### ISSUE THREAD

**Issue by tboo** [uber/ludwig#120]
Hi -

First of all, thanks for the great work. A fantastic tool box. I am struggling to change the optimizer. E.g.   

```
ludwig train --data_csv annotations_all_zoom.csv --model_definition "{input_features: [{name: image_path, type: image, encoder: stacked_cnn}], output_features: [{name: class, type: category}], training: {optimizer: {type: sgd, lr: 0.0004, nesterov: True}, reduce_learning_rate_on_plateau: 10, early_stop: 10, learning_rate: 0.0004, batch_size: 32}}"
```

leads to
```
 Traceback (most recent call last):  
   File "/usr/local/bin/ludwig", line 11, in <module> 
  load_entry_point('ludwig==0.1.0', 'console_scripts', 'ludwig')()  
  File "/usr/local/lib/python3.5/dist-packages/ludwig-0.1.0-py3.5.egg/ludwig/cli.py", line 86, in main 
  File "/usr/local/lib/python3.5/dist-packages/ludwig-0.1.0-py3.5.egg/ludwig/cli.py", line 64, in __init__
  File "/usr/local/lib/python3.5/dist-packages/ludwig-0.1.0-py3.5.egg/ludwig/cli.py", line 70, in train
  File "/usr/local/lib/python3.5/dist-packages/ludwig-0.1.0-py3.5.egg/ludwig/train.py", line 663, in cli
  File "/usr/local/lib/python3.5/dist-packages/ludwig-0.1.0-py3.5.egg/ludwig/train.py", line 151, in full_train
  File "/usr/local/lib/python3.5/dist-packages/ludwig-0.1.0-py3.5.egg/ludwig/utils/defaults.py", line 162, in merge_with_defaults
  File "/usr/local/lib/python3.5/dist-packages/ludwig-0.1.0-py3.5.egg/ludwig/utils/defaults.py", line 119, in get_default_optimizer_params
ValueError: Incorrect optimizer type: sgd
```
I can call the default adam optimizer this way as well and it works. Am I missing something?

**Comment by w4nderlust** [comment]
Thank you!
I pushed a fix so that now you can use the `sgd` type.
Anyway your model definition won't work, for a couple reasons (I should probably detail this better in the documentation):
1. all the optimizer parameters can be specified there in the optimizer dictionary, everyone but learning_rate. The reason is that Ludwig has a different way to deal with the learning rate, passing a placeholder to the optimizer and modifying the learning rate outside tensorflow with a specific logic (for instance reducing it when validation accuracy platoes). So don't pass your learning rate inside optimizer, but inside training, and Ludwig will take care of it.
2. TensorFlow's GradientOptimizer does not have a momentum parameter. In TF in order to use a sgd with momentum, there's a different optimizer called [MomentumOptimizer](https://www.tensorflow.org/api_docs/python/tf/train/MomentumOptimizer). Ludwig wraps this optimizer with the keyword `momentum`.
Given these two reasons, the correct model definition would be:
```
ludwig train --data_csv annotations_all_zoom.csv --model_definition "{input_features: [{name: image_path, type: image, encoder: stacked_cnn}], output_features: [{name: class, type: category}], training: {optimizer: {type: momentum, momentum: 0.1, use_nesterov: True}, reduce_learning_rate_on_plateau: 10, early_stop: 10, learning_rate: 0.0004, batch_size: 32}}"
```
Let me know if this solves your issue and close it in case.

**Comment by tboo** [comment]
Thanks for the quick fix. Works perfectly now. Also thanks for clarifying the optimizer usage. Since you were linking to the TF documentation of the optimizer classes I was just assuming one could pass these parameters on. You also link the keras optimizers in the documentation which caused the confusion about SGD with momentum I guess

**Comment by w4nderlust** [comment]
Thanks! Glad it solved the problem.
Yeah, I'm not using Keras optimizers. I will clarify in the docs about the specifics of the optimizer options.
