### ISSUE TITLE
Should a Chinese csv file be tokenized first?

### ISSUE THREAD

**Issue by jiangweiatgithub** [uber/ludwig#122]
Before I train or predict, should I tokenize the Chinese csv file? (In Chinese, we do not have an explicit delimiting space between Chinese "words".)

**Comment by w4nderlust** [comment]
Yes I would either suggest to pre-tokenize it and then provide the text with whitespaces inbetween tokens and use `preprocessing: {word_format: space}` inside your text input feature. Or another option could be to use characters instead of words with `level: char`.  It' a model design choice. I've never trained a model on Chinese yet so I'm curious to know how it works and it there are ways to make it easier for you (for instance what python tokenizer do you use for Chinese).

**Comment by w4nderlust** [comment]
Closing due to incativity. Feel free to answer again if you need more assistance.

**Comment by bamba518** [comment]
I noticed you have requirement to install spacy, but spacy doesn't have a chinese model. Would this affect training?

**Comment by w4nderlust** [comment]
No. Read [here](https://uber.github.io/ludwig/user_guide/#text-features-preprocessing) for more details.

**Comment by w4nderlust** [comment]
Release 2.3 of spaCy introduces Chinese tokenization. This commit adds it to Ludwig: https://github.com/uber/ludwig/commit/2ad48fd896a8c46ccfb91c3ffd448f0c442985ee .
