### ISSUE TITLE
Google Colab + Python Interface - ImportError: Cannot load backend 'TkAgg' which requires the 'tk'

### ISSUE THREAD

**Issue by pdsing** [uber/ludwig#137]
I have installed the latest version of Ludwig from the master branch (!pip install https://github.com/uber/ludwig/archive/master.zip). But when I try to import ludwig from LudwigModel (from ludwig import LudwigModel), I still get the import error (ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running).

There is no error when I use the CLI

--
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-21-f06c687442c8> in <module>()
----> 1 from ludwig import LudwigModel

/usr/local/lib/python3.6/dist-packages/ludwig/__init__.py in <module>()
     15 # ==============================================================================
     16 from ludwig.api import LudwigModel
---> 17 from ludwig.cli import CLI
     18 from ludwig.globals import LUDWIG_VERSION as __version__

/usr/local/lib/python3.6/dist-packages/ludwig/cli.py in <module>()
     22 from ludwig import predict
     23 from ludwig import train
---> 24 from ludwig import visualize
     25 
     26 

/usr/local/lib/python3.6/dist-packages/ludwig/visualize.py in <module>()
     30 
     31 from ludwig.constants import *
---> 32 from ludwig.utils import visualization_utils
     33 from ludwig.utils.data_utils import load_json, load_from_file
     34 from ludwig.utils.print_utils import logging_level_registry

/usr/local/lib/python3.6/dist-packages/ludwig/utils/visualization_utils.py in <module>()
     26 from matplotlib.lines import Line2D
     27 
---> 28 mpl.use('TkAgg')  # make matplotlib run on mac os
     29 import matplotlib.patches as patches
     30 import matplotlib.path as path

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in use(arg, warn, force)
   1389         if force:
   1390             from matplotlib.pyplot import switch_backend
-> 1391             switch_backend(name)
   1392     # Finally if pyplot is not imported update both rcParams and
   1393     # rcDefaults so restoring the defaults later with rcdefaults

/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    220                 "Cannot load backend {!r} which requires the {!r} interactive "
    221                 "framework, as {!r} is currently running".format(
--> 222                     newbackend, required_framework, current_framework))
    223 
    224     rcParams['backend'] = rcParamsDefault['backend'] = newbackend

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by ccgos** [comment]
I'm having the same experience.

I installed the latest Ludwig version in Colab using  
`!pip install https://github.com/uber/ludwig/archive/master.zip`

and I still get the following error 
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-38-c3dbb80992c3> in <module>()
----> 1 from ludwig import LudwigModel
      2 
      3 # train a model
      4 model_definition = {input_features: [{name: 'acoustic_data', type: numerical}], output_features: [{name: 'time_to_failure', type: numerical}]}
      5 

/usr/local/lib/python3.6/dist-packages/ludwig/__init__.py in <module>()
     15 # ==============================================================================
     16 from ludwig.api import LudwigModel
---> 17 from ludwig.cli import CLI
     18 from ludwig.globals import LUDWIG_VERSION as __version__

/usr/local/lib/python3.6/dist-packages/ludwig/cli.py in <module>()
     22 from ludwig import predict
     23 from ludwig import train
---> 24 from ludwig import visualize
     25 
     26 

/usr/local/lib/python3.6/dist-packages/ludwig/visualize.py in <module>()
     30 
     31 from ludwig.constants import *
---> 32 from ludwig.utils import visualization_utils
     33 from ludwig.utils.data_utils import load_json, load_from_file
     34 from ludwig.utils.print_utils import logging_level_registry

/usr/local/lib/python3.6/dist-packages/ludwig/utils/visualization_utils.py in <module>()
     26 from matplotlib.lines import Line2D
     27 
---> 28 mpl.use('TkAgg')  # make matplotlib run on mac os
     29 import matplotlib.patches as patches
     30 import matplotlib.path as path

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in use(arg, warn, force)
   1389         if force:
   1390             from matplotlib.pyplot import switch_backend
-> 1391             switch_backend(name)
   1392     # Finally if pyplot is not imported update both rcParams and
   1393     # rcDefaults so restoring the defaults later with rcdefaults

/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    220                 "Cannot load backend {!r} which requires the {!r} interactive "
    221                 "framework, as {!r} is currently running".format(
--> 222                     newbackend, required_framework, current_framework))
    223 
    224     rcParams['backend'] = rcParamsDefault['backend'] = newbackend

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------`

**Comment by w4nderlust** [comment]
Please use the latest code in master, it should solve the issue.

**Comment by pdsing** [comment]
@w4nderlust The issue is resolved. I don't see any error when I import Ludwig model. Maybe it was the cached file.

FYI, when I run "from sys import platform; print(platform)" - I get "linux".

**Comment by pdsing** [comment]
Since I don't see the error, I am closing the issue.

**Comment by nosa999** [comment]
> Please use the latest code in master, it should solve the issue. The reason is that you report
> 
> ```
> 27
> ---> 28 mpl.use('TkAgg') # make matplotlib run on mac os
> ```
> 
> But if you look at line 27 and 28 in master they look like this: https://github.com/uber/ludwig/blob/master/ludwig/utils/visualization_utils.py#L27
> 
> The missing if makes me thing that you are not actually using the code on master. Not sure why, maybe the zip is cached?
> 
> Plus, could you please run `from sys import platform; print(platform)` inside colab and thell me what do you get?
I have the same error in colab

**Comment by w4nderlust** [comment]
> I have the same error in colab

Please provide a link to the colab to reproduce the issue.

**Comment by nosa999** [comment]
https://colab.research.google.com/drive/14f5gmYx8WudZXFHS5RCyogmmVqUhdCrb#scrollTo=7IZTvyEQv7uq&line=1&uniqifier=1
This link is useful?

**Comment by w4nderlust** [comment]
> https://colab.research.google.com/drive/14f5gmYx8WudZXFHS5RCyogmmVqUhdCrb#scrollTo=7IZTvyEQv7uq&line=1&uniqifier=1
> This link is useful?

It isn't accessible.
