### ISSUE TITLE
category predict has missing csv in the results folder

### ISSUE THREAD

**Issue by xumx** [uber/ludwig#152]
Current results folder contains 

- `<field_name>_predictions.csv`
- `<field_name>_probability.csv`
- `<field_name>_probabilities.csv`

`<field_name>_predictions.csv` contains only the top 1 prediction. I seems it should be renamed to `<field_name>_prediction.csv`
a new file should be generated that contains all predictions. For scenarios where we need the top-k results.

The results folder should contain
- `<field_name>_prediction.csv`
- `<field_name>_probability.csv`
- `<field_name>_predictions.csv`
- `<field_name>_probabilities.csv`

**Comment by w4nderlust** [comment]
Thanks for the suggestion.
I read it carefully and I decided I'm going to implement it.
There is no use case I can think of for obtaining all the categories, as if they were not sorted it would be useless, and if they were sorted, the same sorting can be obtained from `<field_name>_probabilities.csv` because the probabilities in that file are sorted according to the ordering in the mapping of category to integer available in `train_set_metadata.json` under the name of the field with the key `idx2str`.
Thank you anyway for the suggestion.

**Comment by xumx** [comment]
Thank you. I was looking for a way to get top-k predictions. 

I did not know that 
> the probabilities in <field_name>_probabilities.csv are sorted according to the ordering in the mapping of category to integer.

Maybe this information can be added to the documentation.

**Comment by w4nderlust** [comment]
Definitely
