### ISSUE TITLE
How to test single value on console

### ISSUE THREAD

**Issue by cesarochoa2006** [uber/ludwig#187]
I have trained a text classifier successfully, inside a docker container. I want to know how i can test a single value without the need of use a .csv file. (I mean, something like

`predict 'some text' ....` 
and then get as console output something like: 
`class1`
)

 My plans are deploy inside the container a rest service that executes bash commands, to use my already trained text classifier.

**Comment by w4nderlust** [comment]
There is no way to do this at the moment. But we are already working on it. It will not look like you are proposing because you will have to load the model every single time you call it and it would be extremely slow. There's already an open issue https://github.com/uber/ludwig/issues/87, so I'm closing this as a duplicate.

**Comment by cesarochoa2006** [comment]
I took a so quickly look at the issues and surely i've missed the issue #87. There is no problem as it is something like i plan to do.

**Comment by w4nderlust** [comment]
Sure no worries. You are welcome to participate in that discussion with your use case, so that we can make sure it is accommodated for :) Closed this just not to duplicate the discussion and then loosing track later on.
