### ISSUE TITLE
Support numbered columns with same data type

### ISSUE THREAD

**Issue by Denniso2** [uber/ludwig#197]
When trying to insert datasets that consist of numerical data organised in columns with a name plus number next to them like this kaggle example [https://www.kaggle.com/c/digit-recognizer/data](url) the yaml file needs thousands of lines to include all the variables.In the example provided every pixel has its own column so you have column names such as pixel455 etc.While it is easy to make a python script to automatically create the required yaml file it would be far easier for a native way to handle this.There is a huge variety of datasets with the same naming convection for their columns.

My idea is to give the user the ability to set a range for similarly named columns  using only one entry on the yaml configuration.Something like this 
`name:  pixel`
`range: [0:1000]`
`category:  numerical`

This will include column names pixel0,pixel1,pixel2 etc.
While I would love to help in the development of such a feature I lack the required knowledge.

**Comment by w4nderlust** [comment]
@Denniso2 thanks for the suggestion. At first glance it looks to me that it is a specific quirk of this dataset, and you already suggested a way around it that revolves in the user implementing a super simple 2 lines of python code script to generate the YAML, which seems like the best solution to me.
Anyway, if you say that this is a common pattern in datasets (even if I kinda believe it's the wrong thing to do (it makes it really hard to use CNNs for this, which would probably be a really good model for this problem), they should just provide the images) I may reconsider this. Could you please provide a list of at least 5 datasets that use this format so that i can compare them, take a closer look and, in case I feel like it's worth the effort, consider this?
Thanks

**Comment by Denniso2** [comment]
It turns out to be harder than I expected to encounter such datasets.Out of the recent kaggle competitions I found the following.
[https://www.kaggle.com/c/santander-customer-transaction-prediction/data](url) Really similar to the previous example but with banking data.
[https://www.kaggle.com/c/home-credit-default-risk/data](url) The flag_document variable 1-25
[https://www.kaggle.com/c/dont-overfit-ii/data](url) An educational dataset.

**Comment by w4nderlust** [comment]
The links are broken unfortunately. Anyway, I see the value of this. It could be added as a rewriting rule. Because it doesn't seem there are a huge amount of use cases, and someone with minimal python knowledge would be able to easily write a workaround this, I don't consider it a high priority task, but I added it in my backlog.

**Comment by Denniso2** [comment]
Thank you for the consideration.Links should be working now.
