### ISSUE TITLE
Ludwig integration on custom platform

### ISSUE THREAD

**Issue by simonefrancia** [uber/ludwig#238]
Hello,
I am trying to integrate some ludwig features inside our platform and I would ask you basically two things:

QUESTION 1

The first consists in the numpy version: why in requirements.txt ```numpy>=1.15,<1.16``` is specified? what is the main reason? Because in our platform we use latest version of numpy (1.16.1 with pip) and if I'm not wrong, this version creates problem with ludwig:

```ImportError: Missing required dependencies ['numpy']```

Installing ```numpy>=1.15,<1.16``` is ok but it could make conflicts with other features that are in our platform. 

__________

QUESTION 2
This is a technical question: I am trying to implement a regression predictor that has text in input and its output is a two value tuple between 0 and 1 (x , y where 0<x<1 and 0<y<1, formally ). 
This is my model definition: 

```
 'input_features': [ {'name': 'text', 
                            'type': 'text' , 
                            'encoder': 'rnn', 
                            'cell': 'lstm', 
                            'bidirectional': 'true'} ], 
'output_features': [
                                {'name': 'x', 
                                'type': 'numerical'    }, 
                                {'name': 'y', 
                                'type': 'numerical'}
                            ]
```
But in this way I get sometimes outputs (in the inference phase) < 0 or > 1. How can I tell to output_features to produce numerical numbers between 0 and 1 ( sigmoid layer ) ? 

Thanks for your support!

**Comment by w4nderlust** [comment]
Question 1:
Numpy 1.16 had a bunch of bugs that were not making it work with Ludwig. I haven't tried using 1.16.1 and 1.16.2 to check if they solved the bugs. You could install 1.16.2 and run the test suite (how to do it is explained in the developers guide). If tests pass, I could update to 1.16.2 in the next release.

Question 2:
At the moment you can't. I was thinking about adding an additional `clip` parameter to numerical output features that would clip the values to a specific range before outputtting them. That would solve your problem. But in general, it really depends on the loss and the interpretation of the values, if you two values are probabilities, then you want to use `binary` as data type, if they actually are numerical values, using sigmoid is not a good idea because of saturation (the model will learn easily to predict a specific value, like 0.75, but will have a really hard time predicting 0.99 and it is impossible for the model to predict exactly 0 or 1).
If clipping works for you i would mark it as a feature request.

**Comment by w4nderlust** [comment]
I actually run the tests with numpy 1.16.2 and it works fine, so I'm dropping the <1.16 in the next commit.

**Comment by w4nderlust** [comment]
As it was a pretty quick thing to do, I ended up adding a clip parameter to numerical output features too. now you can have:
```
output_features:
-
  name: x
  type: numerical
  clip: [0, 1]
```
Enjoy :)
Closing it but feel free to comment further if needed.

**Comment by simonefrancia** [comment]
Thanks for your support! :) and congrats for your work!

**Comment by simonefrancia** [comment]
Hi @w4nderlust! 
I have some problems in integrating a model inside our platform. I try to explain briefly my problem:

First of all I build a Docker container where I create a training script using LudwigModel and installing all packages in this way: 

```
pip3.6 install ludwig
python3.6 -m spacy download en
```

I created a model that satisfies me, so I would like to export this model in our platform. 
Here comes the strange thing:
for our platform we have our installation pip package pipeline (different from Ludwig) and after doing this, I install ludwig as I described above. 
When I take the pre-trained model and I load it in our platform, there are no errors but the results of prediction on our platform are completely different from Ludwig standalone environment, on the same input data!! 
That's quite strange because all requirements.txt are satisfied and no errors appear. 

If you have some advice or any idea, it would save me!

Thanks!

**Comment by simonefrancia** [comment]
Ok I think I solved. What I did is to use the configuration of the packages of out platform, and with this configuration of package I trained the model, in order to be compatible with it in inference mode. 
Hope that it can be helpful for something in the future!
