### ISSUE TITLE
Support for BERT pre-trained language models

### ISSUE THREAD

**Issue by danielduckworth** [uber/ludwig#246]
BERT models are pre-trained language representations and include many pre-trained models for many languages.

**Describe the use case**
Better quality word representations and language classifiers for languages other than English.

**Describe the solution you'd like**
The "pretrained_embeddings" to support BERT format.

**Additional context**
https://github.com/google-research/bert#pre-trained-models
https://github.com/llSourcell/bert-as-service

**Comment by w4nderlust** [comment]
We went as far as saying we wanted to add elmo and bert in the blogpost that introduced Ludwig https://eng.uber.com/introducing-ludwig/
So yes we definitely want to add them, but it's not about word representations, but the whole pretrained model that needs to be loaded, not just the embeddings. Anyway, we are working on it.

**Comment by danielduckworth** [comment]
Ahh, sorry. I didn't read the blog post. I got introduced via Siraj's YouTube channel.

Yeah, I did a bit more reading and tinkering with BERT and it's a totally different language model.

Looking forward to seeing it in action. Love the work you guys are doing with Ludwig.

**Comment by w4nderlust** [comment]
@danielduckworth thank you!

**Comment by sam-qordoba** [comment]
Is work underway on this?

One way to get a lot of the benefit of something like BERT without needing to have the entire LM in the same place as Ludwig would be [Bert-as-Service](https://github.com/hanxiao/bert-as-service). It seems like having a more generic interface for text embeddings would allow this?

**Comment by w4nderlust** [comment]
Work is on the way.
As much as bert as a service looks nice, it's built for a pretty different purpose, and that's not the way I want to go. The model and the weights need to be loaded inside the model building phase so that weights can be fine tuned. I definitely don't want to be calling services over http when training.
The level of abstraction that ludwig provides and the interface for text encoders are perfectly fine for having bert as any other encoder, there's nothing missing in the current interface that blocks adding bert.

**Comment by w4nderlust** [comment]
This has been added in Ludwig v0.2, Closing.
