### ISSUE TITLE
Add visualization in notebooks / Colab

### ISSUE THREAD

**Issue by lucaventurini** [uber/ludwig#267]
Hi,

I managed to explore all the basic features of this great tool within the GPU-enabled notebooks provided in Google Colab and Kaggle. I was also able to run and view the tensorboard.

The only thing I missed is the visualization, as I didn't manage to find a way to plot from the notebook.
Is there a way to call the CLI functions from python, and make them return a matplotlib plot? In this way they could be visualized with `%matplotlib inline`, or `%matplotlib notebook` in case we need to zoom or interact.

**Comment by w4nderlust** [comment]
@lucaventurini we are planning to add the visualization function to the programmatic api, so you will be able to do that soon.

**Comment by skim2257** [comment]
@lucaventurini you can try `!command` to execute bash commands in google colab / jupyter notebooks

**Comment by w4nderlust** [comment]
That doesn’t solve the issue unfortunately, the images generated by pyplot will not be visible in a notebook

**Comment by dsblank** [comment]
There may be a way to have it easily run in the notebook, and be able to see visualizations. Here is a hack that might be able to be wrapped up nicely so that it would work better. I am also imagining a `--jupyter` flag that could be added in ludwig.contribs:

In a cell:

```python
import sys
sys.argv = ("ludwig experiment --data_csv reuters-allcats.csv --model_definition_file model_definition.yaml".split(" ")) 
import ludwig
ludwig.cli.main()
```
Now you are running in the notebook, with all of the normal Ludwig CLI flags. Maybe this could be a Jupyter magic.

**Comment by floscha** [comment]
Using Ludwig's [visualization](https://github.com/uber/ludwig/blob/master/ludwig/visualize.py) functionality is already possible using its programmatic API. However, it is not quite intuitive nor convenient. Assuming you have finished training a model and stored the results under *results/experiment_run_1* and also enabled inline plotting using `%matplotlib inline`, the following few lines of code will do the trick:
```python
training_statistics = ['results/experiment_run_1/training_statistics.json']
field = []
model_names = ['results/experiment_run_1/model/']
ludwig.visualize.learning_curves(training_statistics, field, model_names)
```
Especially wrapping the paths in lists and the need to specify the unnecessary *field* parameter as an empty list leave some room for API improvement :wink:

**Comment by w4nderlust** [comment]
@floscha  there's a reason why those functions are not provided in the api module: they are not ready for prime time. Anyway there is a reason for thsoe parameters to be lists and there is a reason for having a field parameter (yes, it is used in the code and is useful). As they can be improved, concrete help and contributions would be much more appreciated ;)

**Comment by floscha** [comment]
Hey @w4nderlust, I understand that the *visualize* module is made for internal usage and is definitely not *useless* for that matter 😉However, there appears to be a considerable number of people for which the current way of plotting programmatically seems rather obscure. Especially since its usage differs quite a bit from the CLI commands which do not require lists or an explicit *field* value.

I would be very glad to help with Ludwig's visualization in notebooks. Since you mentioned that you are planning to add visualization to the programmatic API, are there any ideas yet what that API should look like?

**Comment by w4nderlust** [comment]
@floscha the usage doesn't differ at all from the CLI, the functions are exactly the same and the arguments are exactly the same.

The work that needs to be done is the following: each function of the visualization module performs loading of files, data manipulation and visualization of the manipulated data. At the moment the functions for visualization are separate (`utils/visualization_utils.py`), but the current functions in the `visualize` module do both loading and data manipulation. Those two operations need to be separated so that one would programmatically call only the function that calculates the logic with that that has already been loaded.

As an example, the `learning_curves` function would need to get as input, instead of a list of files, just the data columns needed, and an outer function should load files and call this inner function as many times as needed. This will make for a clean api.

**Comment by prakass1** [comment]
One Solution which I did find recently is using below code:

from ludwig import visualize
visualize.learning_curves(['gDrive/Ludwig/results/api_experiment_run_1/training_statistics.json'],None)

This produces output to the cell of a google colab notebook. One problem would be that one would have to read the functions defined visualize and in utils there is the actual plotting by the filename utils/visualization_utils.py as mentioned above already by @w4nderlust  

The screenshot to confirm:

![image](https://user-images.githubusercontent.com/6094960/58631253-44342a80-82e2-11e9-80c6-b0dfff32dc77.png)

**Comment by w4nderlust** [comment]
Thanks for your note @prakass1 . We are currently working on adding an option to save images (there a branch for that, to be merged soon) and in redefining the signature of the functions in `visualize` to make them usable not only by inputting files like you did, but also directly from dataframes/numpy arrays obtained through prediction. Stay tuned

**Comment by prakass1** [comment]
@w4nderlust I am new to the tool. Looking forward to the upcoming changes and probably will provide suggestions to any enhancements :)

Thank you.

**Comment by w4nderlust** [comment]
This PR refactors and exposes the visualization functions: https://github.com/uber/ludwig/pull/427
Closing the conversation, but please feel free to post opinions and feedback, as now the refactoring allows for further improvement much more easily.
