### ISSUE TITLE
LudwigModel destructor missing

### ISSUE THREAD

**Issue by Guufii** [uber/ludwig#274]
Hi,

I am using a LudwigModel in an optimization loop and recognized a leak due to the missing destructor for the LudwigModel Class. The model.close() method only frees the memory of the underlying TF Session but all memory for the model itself still persists.

My suggestion would be add a default destructor like:

def __del__(self):
       pass

Thanks
G

**Comment by w4nderlust** [comment]
Thanks for reaching out about this.
Can you please provide code and instruction in order to replicate your leak issue?
Because at a first glance, after you call `close()` there's no other resource that the object is holding that wouldn't be freed once you get rid of the reference to the model (which happens at the end of your loop / whenever you reassign an object to the variable name. So for this reason the `__del__()` function would be empty and by consequence useless.
If you have a leak my best guess is that you either hold a reference to the object or to some internal variables of the object somewhere else, but instead of guessing it would be easier to actually take a look at the code and figuring it out.

**Comment by Guufii** [comment]
Hi, thanks for your answer. I figured out the the memory leak originated from the fact that the default garbage collection was not working in my implementation. Manually triggering gc.collect() solved the problem. Therefore it was not to do with the missing destructor.

Best 
G

**Comment by w4nderlust** [comment]
@Guufii thanks for the clarification. I'm still wondering why did you have to do that explicitly... Usually I've seen in many places setting variables to `None` to suggest to reduce their reference count and suggest to the garbage collector to collect them, maybe you can give it a try, doing something like `model = None` at the end of the loop. Anyway, glad you solved the issue.
