### ISSUE TITLE
Using Data Visualization Tool inside LUDWIG SDK

### ISSUE THREAD

**Issue by simonefrancia** [uber/ludwig#289]
Hi, 
after my train procedure I would like to save plots of loss and other parameters, but I am using SDK and I didn't find any documentation about this function:
```
def learning_curves(training_statistics, field, model_names=None, **kwargs):
```
Is there a way to save the figure, instead of plotting it? 
I am inside a Docker container and I am not able to see any plot.
Thanks

**Comment by w4nderlust** [comment]
Not sure what do you mean by SDK, I guess the API. No at the moment the visualization functions are not exposed through the API and there is no way to save images.
Both features have already been requested (so this is a duplicate) and it's already in our todo list.
If you want to help, adding those functionalities, in particular the image save one is really easy, I can show you how to do it. Let me know if you're interested, otherwise stay tuned as those features are going to come pretty soon anyway ;)

**Comment by simonefrancia** [comment]
Ok no problem, I thought that it was already implemented. So I think that I will explore json output with training statistics and I will use matplotlib to plot values. Thanks
