### ISSUE TITLE
How do you get the train_set_metadata to initialize a model ?

### ISSUE THREAD

**Issue by George3d6** [uber/ludwig#295]
**Describe the use case**
I'd like to use `train_online` in order to train my models, to have more control over how long training takes. 

My understanding was that in order to do this I should first call `initialize` on the model, and subsequently call `train_online` as many times as I want.

However, calling `initialize` requires either the `train_set_metadata` or`train_set_metadata_json` arguments, and those objects can seemingly only be gotten from calling `train`.

Which means I have to use `train` first, which kind of defeats the purpose.

**Describe the solution you'd like**
I would enjoy an interface for generating the `train_set_metadata` object, or if the `initialize` function would simply be able to accept the dataframe and based on that + the model definition figure out what that object should look like.

**Describe alternatives you've considered**
Calling `train` on a small subset of my dataset and using that as the initialized model. Thought, I'm pretty sure that could cause biasing issues even assuming it worked.

**Comment by w4nderlust** [comment]
It’s in the model directory.

**Comment by w4nderlust** [comment]
@George3d6 let me explain the rationale here. `train_online` was initially added as a way to refine a pretrained model. For that reason it assumes there's a model to start from. Your usecase, training from scratch using training online, is definitely a reasonable one. The caveat is the following anyway: Ludwig need the `train_set_metadata` in order to map data from raw values to tensors. So if, for instance you have 10 classes, it contains a mapping from the name of the class to the integer value. Now, if the model is not provided with it, it wouldn't know how to map the inputs and the outputs. Training on a small subset of the data, also may not work, because if the subset doesn't contain all the values, when encountered those values are going to be mapped to `<UNK>`. So what you actually need is a representative sample of your data to train on to begin with. But you are right, one doesn't actually need to train at all, all is needed is a function that, given a representative sample of the data, provides you with the metadata. Such a function is already available in Ludwig, but it's currently not exposed through the APIs: https://github.com/uber/ludwig/blob/master/ludwig/data/preprocessing.py#L105 . So I guess this feature request could be frames as "expose the preprocessing function to build the metadata", does it sound good to you?
Will add it to the feature request list.

**Comment by George3d6** [comment]
Yes, that seems like what would be needed here for my usecase. If there's not time to add it I can take a look at it when I have a bit more spare time.

**Comment by w4nderlust** [comment]
Even if those are internal functions that are not yet ready for prime time (and are not documented at the moment), you can already use them actually:
```
from ludwig.data.preprocessing import build_metadata
train_set_metadata = build_metadata(
            dataset_df,
            (model_definition['input_features'] +
            model_definition['output_features']),
            model_definition['preprocessing']
        )
```
in this case `model_definition` is assumed to have been merged with defaults before being provided to `build_metadata`. This can be done in 2 ways. You either use the `model_definition` inside your `LudwigModel`:
```
model_definition = ...
model = LudwigModel(model_definition)
merged_model_definition = model.model_definition
```
or you can import and use the `merge_with_defaults` function:
```
from ludwig.utils.defaults import merge_with_defaults
model_definition = ...
merged_model_definition = merge_with_defaults(model_definition)
```
Let me know if this sovles your issue.

**Comment by George3d6** [comment]
That solution seems to work, however, I've stumbled in another issue when implementing it...

**Comment by w4nderlust** [comment]
Which is... ? :)

**Comment by w4nderlust** [comment]
Closing due to staleness. Anyway now one can easily obtain the train_set_metadata from the API.
