### ISSUE TITLE
Saving metadata.json in a specific directory

### ISSUE THREAD

**Issue by avinregmi** [uber/ludwig#308]
I've been using Ludwig python API for a while now. I've noticed it automatically crates metadata.json file. Is there a way to specify where to save that file? I want to save metadata.json in a specific directory. 

Also during the train, there is a parameter for output_directory and seems like it saves the file in the specified directory. Also, there is a save() function which also saves a file in a given directory. Is there a difference between this two approach? 

Thanks

**Comment by w4nderlust** [comment]
@avinregmi the metadata JSON file is saved alongside the HDF5 file, their function is basically to provide a cache of already preprocessed data so that you run your preprocessing once and then forget about it. As Ludwig automaitcally detects if the HDF5 and JSON file are present in the same directory of the CSV file, their location needs to be fixed.
At the same time, ludwig saves a bunch of things in the output directory, including a model directory with weights, hyperparameters and also another copy of the metadata JSON file (`output_directory/model/train_set_metadata.json`) as it is needed by a model when it is loaded. So you can you that metadata file instead is you don't want to save it alongside the CSV data.
Let me know if this solves your issue.

**Comment by avinregmi** [comment]
Hey, @w4nderlust what happens if I'm running multiple instances of Ludwig from the same directory? Will one instance overwrites the others metasata.json file? 
I'm trying to make a local system where multiple people can train different dataset from the same directory.  Will, that create any trouble? Also, are you saying metadata.json file will be created in the same folder as my CSV dataset? 

Thanks for your help!

**Comment by w4nderlust** [comment]
In that case you have 2 options: either you create a HDF5 + JSON for all the dataset beforehand (but that limits user ability to change datatype and for the features and changing preprocessing parameters) or you avoid saving the preprocess files with the `--skip_save_processed_input` parameter.

**Comment by avinregmi** [comment]
@w4nderlust Do I have access to --skip_save_processed_input parameter via Python API?

**Comment by w4nderlust** [comment]
https://uber.github.io/ludwig/api/#train
