### ISSUE TITLE
Documentation changes for num_fc_layers

### ISSUE THREAD

**Issue by prakass1** [uber/ludwig#369]
The user guide documentation has typo errors as null for num_fc_layers. It should be zero throughout.

I have attached a screenshot below:
![issue](https://user-images.githubusercontent.com/6094960/59094727-10c35280-8917-11e9-8f6b-1d785a6c663f.PNG)

These changes should be corrected for other definitions as well

**Comment by msaisumanth** [comment]
@prakass1 the default value for num_fc_layers is null because the user doesn't need to pick a number for it. Users are expected to either use num_fc_layers or fc_layers. 

num_fc_layers being None indicates that the user didn't chose a value for it. Take a look at the explanation for these two arguments:


fc_layers (default null): it is a list of dictionaries containing the parameters of all the fully connected layers. The length of the list determines the number of stacked fully connected layers and the content of each dictionary determines the parameters for a specific layer. The available parameters for each layer are: fc_size, norm, activation, initializer and regularize. If any of those values is missing from the dictionary, the default one specified as a parameter of the encoder will be used instead. If both fc_layers and num_fc_layers are null, a default list will be assigned to fc_layers with the value [{fc_size: 512}, {fc_size: 256}]. (only applies if reduce_output is not null).

num_fc_layers (default null): if fc_layers is null, this is the number of stacked fully connected layers (only applies if reduce_output is not null).


For more details: https://uber.github.io/ludwig/user_guide/#parallel-cnn-encoder

**Comment by w4nderlust** [comment]
@msaisumanth explained in detail, closing this.
