### ISSUE TITLE
Unnecessary spacing in github.io footer

### ISSUE THREAD

**Issue by IgorWilbert** [uber/ludwig#371]
**Describe the bug**
The style of the footer on github.io pages does not look right

**To Reproduce**
1. Go to https://uber.github.io/ludwig/ and https://uber.github.io/ludwig/examples/
2. Scroll to the bottom
3. See error

**Expected behavior**
They should have the same style.

**Screenshots**
Wrong:
![wrong](https://user-images.githubusercontent.com/42987854/59105866-51b56a00-890b-11e9-82ba-804482eb4024.JPG)
Right:
![right](https://user-images.githubusercontent.com/42987854/59105878-5548f100-890b-11e9-8b45-2983d7188a96.JPG)

**Environment (please complete the following information):**
 - Browser: Firefox 67.0.1 (64-bits) (also happens in MS Edge and Google Chrome)
 - Screen: 1440 x 600
- OS: Windows 10

**Additional context**
This was probably optimized for another device/screen size. I would like to know if would be useful to implement some responsive styles or just change padding/font size etc.

**Comment by IgorWilbert** [comment]
If this issue is valid I'd like to work on it. Thanks!

**Comment by w4nderlust** [comment]
@IgorWilbert thanks for letting us know!
Actually the problem is a little bit more complex: the landing page has a custom css and html that doesn't really fit with the rest of the website, which is built with mkdocs-material.
So at the moment the footer fits well with the style of the homepage, but as you noticed it is different from the style of the other pages because of spacing.
You are welcome to give it a try to make them behave in the same way, but in general it would be better if someone with frontend skills would be willing to undertake the task of making the landing and the other pages use the same css and look more similar.
Unfortunately this is as far as my frontend skills go, so if there's someone else who wants to undertake the task i would be really glad to support their work as much as possible.

**Comment by IgorWilbert** [comment]
Thank you @w4nderlust ! To be honest, I believe I have more experience with front-end than back-end, so I'd be glad to help you with this task. However, I've some doubts:

- Would you like them all to have the style of the homepage, the other pages or something in between?
- What are the steps to run the documentation website? (I could not find them) I have `python` and `pip` installed, so I guess I only need to run `pip install mkdocs`, `cd` into some part of the project and run `mkdocs serve`? Thanks!

**Comment by w4nderlust** [comment]
The instructions are here: https://github.com/uber/ludwig/tree/master/mkdocs
To begin with I believe making the mkdocs and the landing page parts more similar would be great.
In particular having the footer and the top nav bar in the landing page cover all the width like the other pages will make them more consistent, and also have the same font size.
Another important thing is that now the assets for the two are scattered in different directories, consolidating would be great. Finally, when mkdocs generates its js and css files, sometimes it changes their names including some codes, I believe those are hashes of the mkdocs version or something similar. In the landing page I import them manually, but it would be great to find a way to import them automatically to avoid having to change the html of the landing page manually every time.
If you could help with those things, it would amazing.
