### ISSUE TITLE
Dimension mismatch of embedding matrix when model_load_path is used because of vocabulary mismatch

### ISSUE THREAD

**Issue by abc1110** [uber/ludwig#465]
@w4nderlust 
**Describe the bug**
I have made a model using pretrained embeddings (GloVe.6b.50d). I have now built a larger training dataset and want to retrain the model by initialising weights using earlier trained model and so i am using `--model_load_path` command. 

But I am running into an "**InvalidArgumentError  : indices[111,11] = 3441 is not in [0, 3172)**" 

**To Reproduce**
Following code is run: 

`ludwig experiment --data_csv datasets/train_set.csv --model_definition_file test_model_definition.yaml --model_load_path results/experiment_run_2/model`

YAML definition: 
```
input_features:
    -
        name: text
        type: text
        level: word
        encoder: stacked_parallel_cnn
        embedding_size: 50
        pretrained_embeddings: home/abc/mystuff/datasets/glove.6b.50d.txt

output_features:
    -
        name: class
        type: category

training:
    -
        early_stop: 10
```        

**Environment:**
 - OS: Windows 10 
- Python version : Python 3
- Ludwig version : ludwig v0.1.2

**Full error message ouput:**

`InvalidArgumentError (see above for traceback): indices[111,11] = 3441 is not in [0, 3172)`
         `[[node text/embeddings_lookup (defined at /home/abc/mystuff/myenv/lib/python3.6/site - packages/ludwig/models/modules/embedding_modules.py:134) ]]`

**Comment by w4nderlust** [comment]
Looking into it.

**Comment by w4nderlust** [comment]
An update: I tested training a model with those same embeddings and then loading it with `model_load_path` to train a new model on the same data and it works fine.
I guess that your problem stems from the fact that you are using a different dataset, with a different vocabulary size. When you specify pretrained embeddings, ludwig intersects the vocabulary in the embeddings file with the vocabulary in the training data and keeps only those embeddings in the intersection and initialized the ones that are in the training data and are not in the embeddings file. So the resulting matrix can have a different size than the embeddings file (usually smaller, but in some cases it could be bigger).
When you try to train a new dataset, the vocabulary size is different so the size of the embedding matrix within the model would not match.
I'm thinking about what could be a good strategy for those cases, will keep you posted.

**Comment by abc1110** [comment]
Hi Piero,

Thanks a lot of the update. So if I've understood you correctly, given the current situation and model architecture if I get more training data it would be best to re-train the model from scratch with all the training data combined and not simply carry out an incremental training of the model.

Do let me know if my understanding is correct, although I do hope a solution comes for it as my data set is quite large now and it would be computationally expensive to train the model each time.

Thanks a lot!

Best,

Aneri Parikh


On 09-Oct-2019 02:56, Piero Molino <notifications@github.com> wrote:

An update: I tested training a model with those same embeddings and then loading it with model_load_path to train a new model on the same data and it works fine.
I guess that your problem stems from the fact that you are using a different dataset, with a different vocabulary size. When you specify pretrained embeddings, ludwig intersects the vocabulary in the embeddings file with the vocabulary in the training data and keeps only those embeddings in the intersection and initialized the ones that are in the training data and are not in the embeddings file. So the resulting matrix can have a different size than the embeddings file (usually smaller, but in some cases it could be bigger).
When you try to train a new dataset, the vocabulary size is different so the size of the embedding matrix within the model would not match.
I'm thinking about what could be a good strategy for those cases, will keep you posted.

**Comment by w4nderlust** [comment]
@abc1110 yes, at the moment that's the best solution. The main reason is the difference in the vocabularies of the datasets, which means difference in size of the embedding matrix. I could actually make it so that the vocabulary keeps being the one of the first model, but then all new words that don't appear in the old datasets would be mapped to `<UNK>` which, depending on the amount of overlap of the two vocabularies, could be much worse than just training on the concatenation of the datasets.
I'm now considering a solution where the new vocabulary is calculated, the union with the old vocabulary is performed, the words in the old vocabulary already have vectors and they are kept while the new words have randomly initialized vectors. This seems like the best solution, but implementing it in TF1 is not triviel, because i for loading the pre-trained model I just do
```
if self.weights_save_path:
    self.restore(session, self.weights_save_path)
```
which is definitely not sufficient.
I may end up postponing this change until after porting to TF2, as it could make it much easier.

Also, just to clarify, the issue does not depend on the fact that you originally loaded the embeddings, it depends on the way the embedding matrix is constructed in Ludwig (so I'm changing the title of the issue).

**Comment by w4nderlust** [comment]
Actually i thought of a possible solution, please let me know if it is a good enough workaround.
I can add an additional parameter `use_pretrained_embedding_vocab: false`. If set to false, the behavior is the current one. If set to true, instead of using the vocabulary of the training data, the vocabulary of the pre-trained embeddings will be used. This will make the model most likely much larger (because all millions of embedding from the glove file will be loaded for instance), and all words that are in the training set, but do not appear in the pre-trained embeddings vocabulary will be mapped to `<UNK>`. This shouldn't be a huge problem because the vocabulary of the pre-trained embeddings is usually pretty large and comprehensive. Then when you load a pretrained model trained in this way, I will add a check so that the vocabulary of the pre-trained model will be used. This is also a relatively generic solution because, even if you don't specify pre-trained embeddings, when loading a pre-trained ludwig model, there will not be errors like the one you are experiencing. The only last corner case would be when the user specifies both a pre-trained model to load and pre-trained embeddings to load. In this case, the pre-trained Ludwig model will have priority.
I know it's a bit confusing for someone who doesn't know much about Ludwig internals, but at least from the point of view of functionality, does this makes sense to you? Would you be happy with such a solution?

**Comment by w4nderlust** [comment]
@abc1110 I was trying to replicate your error to add the functionality i was writing about in the previous post, but couldn't actually replicate, even if I created ad hoc 2 datasets with a vocabulary of 3 with 2 overlapping characters 1 that is only in the first dataset and one that is only in the second dataset, which should be the issue you are facing. So it could be the case that the problem you are facing has already been solved on master, albeit what would happen is that the vocabulary of the pre-trained model will be used, so if you have new words they will be mapped to UNK but there will not be errors.
Can you please verify if that's the case by installing ludwig from master and retrying? `pip uninstall ludwig & pip install git+http://github.com/uber/ludwig.git`. Alternatively, could you provide your data or a sample of it with which I can reproduce the issue? Obfuscated data with text replaced by random strings is fine too if your data is sensitive and cannot be openly shared.

**Comment by w4nderlust** [comment]
I ended up implementing a  cleaner and simpler solution.
Now you can specify you glove file also as vocabulary, Ludwig will use only the first column as entry in the vocabulary. This way, when you specify a pre-trained glove file you can decide to use its entire vocabulary instead of the interaction between what's in the training data and what's in the glova vocabulary like it happens now.
In your use case, it means you will load the pre-trained embeddings, use the full vocabulary, save the model, load it as a pre-trained model and the whole vocabulary will be used also when you finetune on the new data.
To achieve this you have to change your YAML as follows:
```yaml
input_features:
    -
        name: text
        type: text
        level: word
        encoder: stacked_parallel_cnn
        embedding_size: 50
        pretrained_embeddings: /home/abc/mystuff/datasets/glove.6b.50d.txt
        preprocessing:
            word_vocab_file: /home/abc/mystuff/datasets/glove.6b.50d.txt

output_features:
    -
        name: class
        type: category

training:
    -
        early_stop: 10
```
This will train a model with the full glove vocabulary. Then when you load this model with `load_model_path` to train on new data, the vocabulary in the new data would not be considered, and the full glove vocabulary from the pre-trained model will be used.
I suggest you to set `embeddings_on_cpu: true` when you use glove embeddings and vocabulary, as otherwise they may exceed the size of the memory of your GPU.
This should solve your issue. Please feel free to post or reopen if there are further problems.

**Comment by abc1110** [comment]
@w4nderlust Thanks for the YAML code, I will try and implement it on my dataset and give an update if it works or not.

**Comment by w4nderlust** [comment]
To test it out remember to uninstall ludwig first and then install from
master with pip install git+http://github.com/uber/ludwig.git

On Fri, 11 Oct 2019 at 00:51, abc1110 <notifications@github.com> wrote:

> @w4nderlust
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_w4nderlust&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=w__2sgndJEQQE3HFRTNKWIbAFtW2yfPPAHNkScLBt3Y&s=WKS-6PNj9lyyh7f8izAH4jaPzExXITQwtQaYKIL3nyA&e=>
> Thanks for the YAML code, I will try and implement it on my dataset and
> give an update if it works or not.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uber_ludwig_issues_465-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAACVISCKNOJLYKMTOCUVBTLQOAV7LA5CNFSM4IHYZFP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEA7FOGI-23issuecomment-2D540956441&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=w__2sgndJEQQE3HFRTNKWIbAFtW2yfPPAHNkScLBt3Y&s=D2yE4RgkZi9UwnjeUoRTxa6kx-GDX8egAhKqnVXBLLw&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AACVISH3PABKBITT572RUI3QOAV7LANCNFSM4IHYZFPQ&d=DwMCaQ&c=r2dcLCtU9q6n0vrtnDw9vg&r=RrWxefUdVFeb7Dpg6EF4Ug&m=w__2sgndJEQQE3HFRTNKWIbAFtW2yfPPAHNkScLBt3Y&s=IKTqIAJtsVzLlJ8UgCqEri33Ry6Q2xXAHnNiHg7iFRY&e=>
> .
>
-- 
----
Piero Molino
Sr Research Scientist
UBER AI Labs
