### ISSUE TITLE
Uber Ludwig not training my model.

### ISSUE THREAD

**Issue by doedelsnj** [uber/ludwig#515]
I did everything like it was shown in the video: https://www.youtube.com/watch?v=uSOsos2eKHI. But as soon as i'll try to train the model and run the command "ludwig train -md model_definition.yaml --data_csv Tweets.csv " it says AssertionError: Model definition does not define any input features and doesn't train my model. Even though i have defined the input features.

Thanks for the help.

[Archiv.zip](https://github.com/uber/ludwig/files/3597626/Archiv.zip)
(YAML and csv files)

 - OS: MacOS 10.14.5
- Python 3.74
- Ludwig 0.2.1

Terminal Output:

https://github.com/TannerGilbert/Tutorials/files/3596076/Terminal.Output.txt

**Comment by msaisumanth** [comment]
@doedelsnj  Two things: 
1. the input_feature name needs to match the column name in the csv. same for output features. change the input feature name to 'text' and output to 'airline_sentiment'
2. you're using the wrong command line argument for model_definition. Since you're providing model definition in a file, you should use '-mdf' instead of '-md'. 

I verified model training works with these changes.
