### ISSUE TITLE
Troubles with visualisation

### ISSUE THREAD

**Issue by SSicaaJL** [uber/ludwig#520]
Hello, I am having troubles with visualising using the few commands of code here, I am hoping you could advise me. 

**This is the training and testing codes:**
![rain troubleshoot1](https://user-images.githubusercontent.com/43140909/65309715-396a1200-dbbf-11e9-9227-3aa1701f40e7.JPG)
**This is the one for learning curves which I have no problems in generating**
![rain troubleshoot2](https://user-images.githubusercontent.com/43140909/65309782-5dc5ee80-dbbf-11e9-8f0b-721dba9eb1f3.JPG)
**For Learning curves**
I cannot seem to figure what files i could use for the probability and ground truth and not sure if they are the correct ones. 
![rain troubleshoot3](https://user-images.githubusercontent.com/43140909/65309988-d331bf00-dbbf-11e9-96fa-e249a1bd97e7.JPG)
**For Confusion matrix**
Same issue, not sure which are my fields are, hence I am getting many errors.
![rain troubleshoot4](https://user-images.githubusercontent.com/43140909/65310057-01af9a00-dbc0-11e9-96a7-10876e6ba00f.JPG)

For further information, the only data that appear in my results are as follows:

![rain troubleshoot5](https://user-images.githubusercontent.com/43140909/65310176-49362600-dbc0-11e9-9097-9d0dd283e25a.JPG)
![rain troubleshoot6](https://user-images.githubusercontent.com/43140909/65310179-49362600-dbc0-11e9-88d5-1e9f7b7a1a7e.JPG)

It would be great if you could advise me . Thank you very much.

**Comment by msaisumanth** [comment]
@SSicaaJL we're going to work on improving the visualization documentation. In the meantime, follow this for confidence thresholding:

```code
def confidence_thresholding_cli(
        probabilities,
        ground_truth,
        ground_truth_split,
        field,
        **kwargs
):
    """Load model data from files to be shown by confidence_thresholding.

    :param probabilities: Path to experiment probabilities file
    :param ground_truth: Path to ground truth file
    :param ground_truth_split: Type of ground truth split - train, val, test
    :param field: Target prediction field
    :param kwargs: model configuration arguments
    :return None:
    """
```

for confusion matrix:
```code
def confusion_matrix_cli(test_statistics, ground_truth_metadata, **kwargs):
    """Load model data from files to be shown by confusion_matrix.

    :param test_statistics: Path to experiment test statistics file
    :param ground_truth_metadata: Path to ground truth metadata file
    :param kwargs: model configuration arguments
    :return None:
    """
```

sorry for the late response.

**Comment by w4nderlust** [comment]
@SSicaaJL
The filed parameter is the name of the column / output feature you want to visualize. In your case it would be `field = "RainTomorrow"`.

For the learning curves:
I don't know how you obtained train_stats. If you got it from the API `model.train()` you can use it as it is, otherwise you just have to load the `training_statistics.json` file that was saved at the end of training. After you do that `learning_curves(train_stats, field, output_directory=output_dir, file_format='png')` should work.

For the confusion matrix:
just use the field parameter as i specified and your command should work.

Will update the docs to try to explain better what is `field`.
