### ISSUE TITLE
Incorrect formatting of visualization api calls in Ludwig documentation

### ISSUE THREAD

**Issue by jimthompson5802** [uber/ludwig#547]
**Describe the bug**
Most visualization api parameters documentation are not correctly formatted.

**To Reproduce**
Example of incorrect formatting of documentation: https://uber.github.io/ludwig/api/visualization/#learning_curves
<img width="962" alt="api_doc_incorrect_format" src="https://user-images.githubusercontent.com/1425269/67630148-3c5cc000-f859-11e9-9d2e-8d4e2893dd0b.png">

**Expected behavior**
Correct formatting of the parameter list

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOs 10:15
 - Version 10.15
- Python version N/A
- Ludwig version: 0.2.1

**Additional context**
I've researched and modified the module `code_doc_autogen.py` to correctly format the visualization api parameters.  In addition, minor updates were made to the docstring for functions in `visualize.py`.  Here is an example generated by the revised `code_doc_autogen.py`:
<img width="856" alt="api_doc_correct_format" src="https://user-images.githubusercontent.com/1425269/67630218-e426bd80-f85a-11e9-836f-acb3440c0e6d.png">

If this looks reasonable, I'm willing to finish up the work to correctly format the visualization api calls and submit a PR.    Any guidance will be appreciated.

**Comment by w4nderlust** [comment]
Yes it looks fine, thanks for being willing to help on this. In order to generate the API pages we use a script  in the mkdocs directory. The instructions on how to generate the docs are in the readme in the mkdocs directory too. Please don't touch them, but just modify the docstrings in visualization.py. For a reference about the syntax to follow, look at the syntax of the docstrings in api.py as those are visualized correctly. If you follow exactly the same structure things will look great and achieving this task would be super simple :) Let me know if there's something unclear in the process, I can help you out in case.

**Comment by jimthompson5802** [comment]
@w4nderlust  I understand that I should only modify the docstrings in `ludwig/visualize.py` to correct the formatting errors.  

Initially, I limited my work only in the docstrings.  After modifying the dcostrings, I ran `mkdocs/code_doc_autogen.py` per instructions in `mkdocs/README.md`.  However, this still did not correctly generate `mkdocs/docs/api/visualization.md`.  

After reviewing `mkdocs/code_doc_autogen.py`, it appears that there was some code missing to process the visualization function specifications.  Working with the current design of `code_doc_autogent.py`, I added about half-dozen lines of code to recognize the specification of the visualization functions.  

After making this change, `mkdocs/docs/api/visualization.md` now reflected the correct formatting for the visualization parameters.

I'll post a PR with the change so that you can see what changes I made to the docstrings in `ludwig/visualize.py` and `mkdocs/code_doc_autogen.py`.
