### ISSUE TITLE
Is it possible to export the feature engineering pipeline and model as tensorflow code?

### ISSUE THREAD

**Issue by hhbyyh** [uber/ludwig#557]
I'd like to export the feature engineering steps and model as python code, so I can make further customization. It will be great if we can automatically generate the training and prediction code.
1. Is it possible with current code base?
2. Will it be considered in future development?

Thanks and great work!

**Comment by w4nderlust** [comment]
#hhbyyh ludwig is all written in python, so you have all the code you want and you can change whatever you want :) Maybe I'm not getting your question really,

**Comment by hhbyyh** [comment]
Thanks for the response. @w4nderlust 
Suppose I trained the model with:
`ludwig train --data_csv path/to/file.csv --model_definition "{input_features: [{name: doc_text, type: text}], output_features: [{name: class, type: category}]}"`

After the training I got the saved model and training logs. Yet I want to add some customized operation to feature engineering step or model, the best way in my mind would be to export the training code from ludwig add add my change to it. That means besides the trained model, I would also like to have the code that generates the model (preferably in TF API). Is it possible now?

**Comment by w4nderlust** [comment]
I see. At the moment and for the forseable future, the preprocessing is performed in python so there is no way to export it as tf code. if you want to modify it, I suggest you to modify the python code directly, check `ludwig/data/preprocessing.py` to see what happens when Ludwig does the preprocessing and play around with it. Consider that each feature has it's own preprocessing that you can find in the BaseFeature object in each `/ludwig/feature*_feature.py` module.
One thing i would suggest you anyway is to avoid changing the preprocessing after you trained a model, as discrepancies in the pipeline you use for prediction may result in poor results. If you want to change the pipeline do it before training, and then keep the same one when predicting. Also consider that if you call the `LudwigModel.predict()` method from the programmatic API, the pipeline of the trained Ludwig model is applied automatically for you.
Marking this as a feature request, but also as a wontfix, at least for now. Feel free to keep asking questions if you have more.

**Comment by hhbyyh** [comment]
Thanks a lot for providing the answer. I'll close the issue now.
