### ISSUE TITLE
about UNK and hits_at_k

### ISSUE THREAD

**Issue by Kantshun** [uber/ludwig#590]
I'm doing a classification task. in my ludwig model's result, there is one more class appear, the UNK class. could anyone explain what is UNK?
moreover, what is hits_at_k?

**Comment by w4nderlust** [comment]
UNK is a sink class that deals with all the cases where at test time you have a class that was not present at training time. You can also set a threshold on the prequency of classes and all the ones less frequent than a certain amount will be replaced with UNK.

Hits at k is the accuracy considering any prediction in the first k to be correct instead of the argmax. It is useful if you have a model that fuels more than one prediction to a UI, your model behaves well if any of the k predictions is correct.
