### ISSUE TITLE
how to use collect_weights, what is the meaning of --tensor and how to I get one tensor?

### ISSUE THREAD

**Issue by surendra1472** [uber/ludwig#595]

**Comment by msaisumanth** [comment]
@surendra1472 please provide more details about what you're trying to do.

**Comment by w4nderlust** [comment]
As explained in the [User Guide](https://uber.github.io/ludwig/user_guide/#collect_weights) the command collects the weights of a specific tesnor in the model. In order to know which tensor, you have to specify its name. In order to know the name you can either used logging level debug when building the model (and the name of the tensors will be displayed when the model is built) or open the model with the tensorboard and use the graph view to figure out the tensor name.

**Comment by w4nderlust** [comment]
Closing due to staleness, feel free to reopen if this is still an issue.
