### ISSUE TITLE
In preprocessing, when .hdf5 is not existing, split is ignored

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#609]
If split is not "full" (ie: I only want to use training or validation or test data to run a test, for example) and I don't have a .hdf5 file, data is loaded anyway, but without honoring the split request.

Reference: https://github.com/uber/ludwig/blob/master/ludwig/data/preprocessing.py#L804-L840

**Comment by carlogrisetti** [comment]
This can be validated running a test on a .csv dataset without a .hdf5 and then giving also the .hdf5
In a situation where you have 1000000000 train examples and 1 validation example, running a test with --split validation gives the same results as a --split full when .hdf5 is missing, and works well if a corresponding .hdf5 is already present.

**Comment by w4nderlust** [comment]
Let me look into it

**Comment by w4nderlust** [comment]
Just to confirm the issue: the data you are providing to test/predict has a split column, right? because if the data has no split column, this behavior is expected.
Just to be sure, can you actually provide either a script or a notebook or anything to replicate this that is self contained? I'm happy to look into it but want to be sure of what the actual issue is.

**Comment by w4nderlust** [comment]
I created a PR that fixes this. The logic is the following: if the split is specified to be not `full` and the CSV contains a `split` column, the prediction will happen only on the data split. If the CSV does not contain a split column, the full data will be used and a message will be displayed to notify the user about this.

**Comment by w4nderlust** [comment]
Merged it, the issue should have been fixed, let me know if you have other problems.
