### ISSUE TITLE
Progress bar using programmatic API

### ISSUE THREAD

**Issue by trojan03** [uber/ludwig#621]
**Describe the bug**
I wonder if there is any way to output the progress bar using programmatic API in Python similar to when calling `ludwig train` from CLI? I already tried setting `logging_level=logging.DEBUG` when calling the train() function but it only outputs the tf-stuff. I would appreciate any help. Thanks!

**To Reproduce**
```python
statistics = model.train(dataframe, logging_level=logging.DEBUG)
```

**Expected behavior**
A progress bar similar to when calling `ludwig train` from CLI.

**Environment (please complete the following information):**
- OS: Windows
- Version 10
- Python version 3.6.8
- Ludwig version 0.2.1

**Comment by msaisumanth** [comment]
@trojan03 Not sure what's going on. When you set the logging level to to debug, it shouldn't disable the progress bar. 

Are there any error/warning messages in the logs?

**Comment by w4nderlust** [comment]
@trojan03  since the latest version we changed the way logging works. Now the logging level has to be set in the `LudwigModel` initializer. There is also a `set_logging_level` method if you want to change the logging level after initialization. Refer to the [API docs](https://uber.github.io/ludwig/api/LudwigModel/). Please let us know if this solves the problem.

**Comment by msaisumanth** [comment]
shoot, yes! Didn't realize the command mentioned there was model.train.

You need to set the logging level during model initialization. 

```code
model = LudwigMode(..., logging_level = logging.DEBUG)
```

**Comment by trojan03** [comment]
Thanks! My mistake, I did not realize that setting the logging_level was referred to initialization of the model. Works as expected!
