### ISSUE TITLE
Newbie Help

### ISSUE THREAD

**Issue by Budapresst** [uber/ludwig#657]
Greetings... 
I'm new to Ludwig and ML in general.  I'm looking for some guidance, because my first experiment didn't work. Please let me know if this is not the proper forum for help. 

I have everything installed on my Linux server no errors so far.  I'm using the CLI and decided to see if I could "predict" antonyms. I created a CSV with ~5000 words and their opposites:
```
word,opposite
agglomerate,scatter
aggrandize,depress
aggregate,dissipation
aggression,resistance
```
I created a yaml file:
```
input_features:
    -
        name: word
        type: text

output_features:
    -
        name: opposite
        type: text
```
I trained Ludwig with the following command:
```
ludwig train --model_name OPPOSITES --data_csv opposites.csv --model_definition_file opposites.yaml
```
No apparent problems so far.... 
Next, I created a CSV to test the training:
```
word
agglomerate
```
Lastly, I ran the predict command:
```
ludwig predict --data_csv predict.csv --model_path results/experiment_OPPOSITES/model/
```
There were no errors, but the resulting opposites_predictions.csv just had 2 lines:
```
soothe,<PAD>
soothe,<PAD>
```
"soothe" is one of the ~10500 words in the original training CSV, but obviously not relevant to my prediction test... 

That's it... Being new to Ludwig, I don't know what I'm doing wrong or even which direction to go to resolve things... Any direction or advice would be greatly appreciated.

**Comment by w4nderlust** [comment]
Is your dataset made of all unique inputs and outputs? In that case, if you are not using some pretrained embeddings it's really unlikely you are going to obtain a model the produces opposites for words it has never seen, as it does not have any representation for an unseen word and has never predicted a word that's the opposite of the specified word.. Those words are unique and treated like categories so the overall approch is hopeless. On the other hand you could set the level to characters and the model could learn something from it, like that in many cases preponing "anti-" to a ward gives it's opposite (I'm not really sure this is the correct example, as antiwar is not the oposite of war, but what I meant is that there could be some character sequences that can be learned for producing opposites in a limited number of cases).
If on the other hand you used word embeddings you could learna function, maybe even a single direction in the multidimensional embedding space, that let's you figure out the opposite. I would collect all the embeddings of those words and compute `avg_dir_opp = avg(word-opposite)` to obtain a direction vector that then you cna add to a word to obtain the position in space like `new_pos = new_word + avg_dir_opp` and then compare that position with all the other embeddings to figure out among all words which one is the opposite the the new word. A similar approach is used in thsi paper, but for computing verb affordances instead of opposite words: https://arxiv.org/abs/1703.03429

**Comment by Budapresst** [comment]
Thank you... Your answer has cleared things up for me.  I knew that my first experiment was rather pointless, but I guess being my first interaction with deep learning, I wanted to see Ludwig repeat output based on controlled input before making the next step and getting into actual predictions.  But, I see now that my model was probably the issue and I will try some more appropriate experiments for my next try.  Thank you very much for the explanation and the link to the affordances paper which was very interesting.
