### ISSUE TITLE
How can I assign test predictions to my input data?

### ISSUE THREAD

**Issue by donfour10** [uber/ludwig#659]
Problem:
When I performed a experiment, I get a csv. file whre I can find the predictions. But I do not know which prediction belongs to which row of my data.
Probably I just do not find the documentation for this because I'm sure there's a description somewhere of how to do that.

Use Case:
I am parsing some Websites from companies all over the world and want to get to know in which subject area these companies operate in. So my input data is a text and my targets are sets of categories. But I do not know how I assign the predictions to my actual data because the prediction.csv-file just get category predictions without any reference.

Soloution:
Maybe you can help me with my problem or you can tell me whre I can find existing documentation for this.

**Comment by ifokeev** [comment]
you're able to`pd.concat` two arrays: one from your ground truth data and the second one with predictions.

Try this:
https://stackoverflow.com/questions/46069709/combining-two-csv-files-using-pandas

**Comment by donfour10** [comment]
Okay, thanks for now, but this is not exactly what i mean. 
The problem I have is that I have no clue to which input the prediction belogs. When I execute a ludwig experiment the data randomly split the data into training, validation and test data (that's what ist says in the docs, so I have much more rows in my ground truth data as in my predictions).

I try to explain it a bit better:

In the prediction.csv I get predictions like that. Just one column with categories.
![image](https://user-images.githubusercontent.com/55831555/77160243-3df88000-6aa7-11ea-9fcd-5644388ad8f4.png)

My input.csv is structured like that:
![image](https://user-images.githubusercontent.com/55831555/77161499-19ea6e00-6aaa-11ea-939b-84f2b4a7fcfa.png)
text -> input
categories -> targets(output)

Now I have predictions but I dont' know how I assign them to the input data. There is no index or anything like that to assign the predictions. So `pd.concat` not really helps me becuase I don't want to just put two files together.

Thanks anyway for your help!

**Comment by ifokeev** [comment]
If you have no index then assign by number of the row. 
When you use `luwdig.predict` you have output the same length as the output.

**Comment by w4nderlust** [comment]
If you provide just the dataset, Ludwig, will split it automatically. If you save the preprocessed data, you can see the split in the hdf5 file that is saved (there's a split column, 0 means training, 1 means validation and 2 means test). This setting is useful if you want to train a model from a dataset and test it on a random split of the data.

In the case where you have already a split, you can either provide the already splitted data with the appropriate parameters `--data_train_csv`,  `--data_tvalidation_csv`, `--data_test_csv`. In this case there's no random split, and the data that is predicted is the test set, the rows are aligned as in the first row of Ludwig prediction is the prediction of the first row of your test set and so on.
Alternatively you can also first train your model and then predict on the test set using two separate commands instead of experiment. All this is explained in the user guide that I suggest you to read https://uber.github.io/ludwig/user_guide/

Let me know if you have further questions, closing this for now, can reopen if you still have issues.
