### ISSUE TITLE
where to get the datasets in your examples?

### ISSUE THREAD

**Issue by MrRace** [uber/ludwig#68]
I want to  follow the [examples](https://uber.github.io/ludwig/examples/) and where to get the datasets  in the examples?

**Comment by w4nderlust** [comment]
Those are just hypothetical examples. There are some dataset that map easily to them, for instance machine translation datasets, image classification ones, omniglot can be used for the siamese examples, several sentiment analysis datasets and so on. A google search will return many more than I can list here. We explicitly tried not to tie to specific datasets, because some of them would require some minimal data monging to be made in a CSV format that is readable by Ludwig, so we tried to avoid that quagmire.
