### ISSUE TITLE
How to define max_seq_length for the BERT encoder?

### ISSUE THREAD

**Issue by danielduckworth** [uber/ludwig#711]
**Describe the bug**
When using the BERT encoder for a text input feature, is the 'word_sequence_length_limit' parameter used? 

The examples given on the BERT github refer to a 'max_seq_length' parameter.

Is this defined at the level of the 'input_features' like the other encoders with the type 'text' or at the level of 'preprocessing' where the tokenizer parameter is defined?

**Additional context**
The documents I'm working with range from 200 - 1200 words so I'm trying to make sure the longest sequencing are being captured when using the bert encoder.

**Comment by w4nderlust** [comment]
@danielduckworth it should be. Now there's a slight weirdness with using `text` the rather than `sequence` in that bert doesn't properly use words, this will be solved in future versions where words, chars and bpes will be treated the same way.
But for now `word_sequence_length_limit` if `text` and `sequence_length_limit`if `sequence` should do the job.

You can define it both at the input feature level or at the global preprocessing level. The difference is that in the global preprocessing it applies to all features of a specific type, while at input feature level it applies only to that specific feature. If you define both, the input feature one overrides the global one.

Consider that 1200 words is very very long for bert, you are likely going to run out memory even if you set the batch size to be very small, so you may want to trade it off.

**Comment by danielduckworth** [comment]
OK, got it, thanks.
