### ISSUE TITLE
Rework Ludwig to use TF2 and Py >= 3.8

### ISSUE THREAD

**Issue by aspenforest** [uber/ludwig#783]
**Is your feature request related to a problem? Please describe.**
I need to use python 3.8, but Ludwig does not work on recent python versions, because TF 1 is not available on Python 3.8.

**Describe the use case**
Use Ludwig with recent python versions.

**Describe the solution you'd like**
Replace TF1 with TF2 in Ludwig.

**Describe alternatives you've considered**
Keep Ludwig outdated and on track to break when TF1 becomes deprecated.

**Additional context**
It would be reasonable to keep updated software, which has not yet become abandonware, lest the dev risks their soft being forced into obsolescence.

**Comment by w4nderlust** [comment]
This is already going on, see the https://github.com/uber/ludwig/tree/tf2_porting branch and the tasks being worked on here https://github.com/uber/ludwig/projects/1 . 

> Describe alternatives you've considered
> Keep Ludwig outdated and on track to break when TF1 becomes deprecated.
>
> Additional context
> It would be reasonable to keep updated software, which has not yet become abandonware, lest the dev risks their soft being forced into obsolescence.

I don't like the tone of these comments. Please refrain to use this tone again.

We have been working on porting Ludwig to TF2 for months, it's not an easy task as TF2 changes entirely the paradigm of its APIs and many choices in Ludwig that were based on the previous paradigm need to be revised and modified.
Moreover, TF2 is still very young and full of problems and missing features, for that reason we waited to actually port until the features we needed from TF1 were ported, as otherwise we would have had to cut features in the new version of Ludwig, and we did not want to do it.
The version Ludwig is currently using, 1.15.3 was release the 18th of May 2020, less than 2 months ago, so the use of words like "obsolete", "obsolescence" and even "abandonware" is entirely out of place.

So you have a few options:

- install Python 3.7 and use the current version of Ludwig
- install from the `tf2_porting` branch, knowing it's still a work in progress
- help in the porting process so that you will be able to use Ludwig with TF2 sooner
- wait without being insulting to developers that put their time into this open source project
